### PR TITLE
Provide MISP and Gitlab in docker-compose

### LINKED ISSUE #21: Integrate MISP and Gitlab in docker-compose
- [x] Integrate MISP (https://github.com/MISP/misp-docker)
- [x] Integrate Gitlab (https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose)

### PR DESCRIPTION
**Pull request by fritterhoff**
Fixes #21

### CODE REVIEW

**Comment by fritterhoff** [comment]
@DerAlexmeister should work so far. 
I've also added the option to disable the certificate checking when connecting to gitlab (that was missing until now?)

You should checkout including the submodule so you can start the project.

**Review by DerAlexmeister — COMMENTED** [review]
Müssen bei Kafka, Zookeeper neo4j etc auch die Submoduls geladen werden und es fehlt ein make Command für GitLab und Misp

**Comment by DerAlexmeister** [comment]
Resolve conflict.

**Comment by fritterhoff** [comment]
> 
> 
> Resolve conflict.

Also done.

**Pull request merged**
